version: '2'

volumes:
  data:
    driver_opts:
      type: none
      device: /home/oka/ext4/OkaHome/docker/nextcloud/volumes/nextcloud_data
      o: bind
  db:
    driver_opts:
      type: none
      device: /home/oka/ext4/OkaHome/docker/nextcloud/volumes/nextcloud_db
      o: bind

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=enoj3dfjadklJLKFHJE
      - MYSQL_PASSWORD=djskl312FJAleij
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
## FOR DEBUG (recovering innodb)
#command: bash -c 'printf "[mysqld]\ninnodb_force_recovery = 6\ninnodb_purge_threads =0\nuser = root\n" > /root/.my.cnf && mysqld'

  app:
    image: nextcloud:20
    ports:
      - 37498:80
    links:
      - db
    volumes:
      - data:/var/www/html
    restart: always
