version: '2'

volumes:
  data:
    driver_opts:
      type: none
      device: /Volumes/4TB/docker/nextcloud_data
      o: bind
  db:
    driver_opts:
      type: none
      device: /Volumes/4TB/docker/nextcloud_db
      o: bind

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=enoj3dfjadklJLKFHJE
      - MYSQL_PASSWORD=djskl312FJAleij
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 37498:80
    links:
      - db
    volumes:
      - data:/var/www/html
    restart: always
